using SummaSQLGame.Models;

namespace SummaSQLGame.Databases
{
    internal class StudentSeeder
    {
        private string[] NAMES = {
        "Alice Johnson",
        "Bob Smith",
        "Clara Martinez",
        "Daniel Lee",
        "Emily Davis",
        "Frank Anderson",
        "Grace Wilson",
        "Henry Brown",
        "Isabel Taylor",
        "Jack White",
        "Karen Garcia",
        "Liam Miller",
        "Megan Hall",
        "Nathan Moore",
        "Olivia Harris",
        "Peter Clark",
        "Quinn Turner",
        "Rachel King",
        "Samuel Martinez",
        "Taylor Adams",
        "Victor Robinson",
        "Wendy Wright",
        "Xavier Scott",
        "Yasmine Lopez",
        "Zachary Young",
        "Ava Thompson",
        "Benjamin Jackson",
        "Chloe Baker",
        "David Adams",
        "Emma Harris",
        "Felix Turner",
        "Grace Walker",
        "Henry Davis",
        "Isabella Lewis",
        "Jake Garcia",
        "Katherine Turner",
        "Leo Martinez",
        "Mia Rodriguez",
        "Nolan Smith",
        "Olivia White",
        "Peyton Wilson",
        "Quincy Taylor",
        "Rebecca Harris",
        "Simon Johnson",
        "Tessa Brown",
        "Ulysses Miller",
        "Violet Clark",
        "Walter Adams",
        "Xena Lopez",
        "Yasmine Moore",
        "Zane Davis",
        "Amelia Wilson",
        "Bryan Smith",
        "Cora Turner",
        "Dylan Lewis",
        "Ella Thompson",
        "Finn Robinson",
        "Giselle Hall",
        "Hudson Young",
        "Ivy Taylor",
        "Jordan Garcia",
        "Kai Anderson",
        "Lila Wright",
        "Milo Harris",
        "Nora Martinez",
        "Oscar Walker",
        "Piper Adams",
        "Quincy Taylor",
        "Riley Jackson",
        "Sofia Baker",
        "Tucker White",
        "Uma Turner",
        "Vincent Robinson",
        "Willow Harris",
        "Xavier Smith",
        "Yara Davis",
        "Zara Turner",
        "Alex Miller",
        "Blake Harris",
        "Carmen Adams",
        "Derek Wilson",
        "Eva Lopez",
        "Felix Thompson",
        "Gemma White",
        "Hugo Clark",
        "Ivy Turner",
        "Jasper Robinson",
        "Kylie Adams",
        "Liam Harris",
        "Mia Turner",
        "Nolan Robinson",
        "Olivia Davis",
        "Preston Smith",
        "Quinn Turner",
        "Ruby Harris",
        "Samuel Walker",
        "Tessa Miller",
        "Ulysses Turner",
        "Violet Clark",
        "Winston Harris",
        "Landon Mitchell",
        "Stella Foster",
        "Asher Pearson",
        "Mila Reed",
        "Cameron McLaughlin",
        "Aurora Dawson",
        "Owen Barrett",
        "Eva Hayes",
        "Lincoln Holland",
        "Hannah Stanton",
        "Easton Thornton",
        "Sadie Vaughn",
        "Maximus Archer",
        "Clara Baldwin",
        "Levi Blackwell",
        "Nova Hampton",
        "Hudson Carrington",
        "Willow Donovan",
        "Kai Randolph",
        "Emery Hayes",
        "Sawyer Blackburn",
        "Ainsley Harper",
        "Paxton McDaniel",
        "Zara Barnett",
        "Jasper Livingston",
        "Aria Cannon",
        "Elias Sinclair",
        "Luna Farmer",
        "Grayson Holloway",
        "Ivy Foley",
        "Dakota Jefferson",
        "Ayla Pruitt",
        "Zane Hutchison",
        "Ruby Leblanc",
        "Augustus Case",
        "Ariana Wiley",
        "Finnegan Sampson",
        "Lila O'Donnell",
        "Ryker Hodge",
        "Amara Middleton",
        "Beckett Saunders",
        "Sienna Whitaker",
        "Knox McPherson",
        "Adeline Finley",
        "Kian Delaney",
        "Layla Carver",
        "Ronan O'Neill",
        "Alessia Pike",
        "Rylan Sheppard",
        "Gemma Cash",
        "Kieran Moffett",
        "Elodie Cote",
        "Cohen Mercer",
        "Lydia Haines",
        "Jaxson Hubbard",
        "Aubree Burnside",
        "Soren Maldonado",
        "Ariella Healy",
        "Mateo Lester",
        "Maeve O'Sullivan",
        "Kyrie Hogan",
        "Daphne Rutherford",
        "Gideon Whitfield",
        "Serena Daley",
        "Colton Kirkland",
        "Elara Byers",
        "Rhys Pritchard",
        "Zoey Dickens",
        "Kaius Harrell",
        "Felicity Galloway",
        "Knoxley Blackwood",
        "Mira Hendricks",
        "Sullivan Coburn",
        "Lia Falconer",
        "Jett Doherty",
        "Evie Brophy",
        "Thatcher Eldridge",
        "Brynn Davenport",
        "Sutton Samuels",
        "Emilia Crowley",
        "Bryce Dyer",
        "Athena Ballard",
        "Zephyr Morley",
        "Phoebe Stafford",
        "Archer Chambers",
        "Maisie Rudd",
        "Harlan Driscoll",
        "Aurora Pollard",
        "Kellen Hatfield",
        "Tessa Milner",
        "Thaddeus Chappell",
        "Adelaide Tillman",
        "Crew Henson",
        "Anastasia Bartlett",
        "Baylor Ortega",
        "Amelie Mayer",
        "Daxton Farley",
        "Freya McAllister",
        "Cassius Mueller",
        "Livia Whitmore",
        "Emerson Strickland",
        "Isla Mathis",
        "Micah Dunlap",
        "Athena Harrell",
        "Cyrus Leach",
        "Nola Blackburn",
        "Kaius Alston",
        "Aurora Bergeron",
        "Kasen Dotson",
        "Elara Mercado",
        "Malakai Cooley",
        "Seraphina Gallegos",
        "Soren Dickinson",
        "Luna McLeod",
        "Daxton Steward",
        "Zara Langley",
        "Jaxson McMillan",
        "Adelaide Merrill",
        "Zephyr Sloan",
        "Harlow Fitzpatrick",
        "Caspian Hodge",
        "Ivy Rangel",
        "Brecken Hensley",
        "Isla Byrd",
        "Baylor Pitts",
        "Alina Knox",
        "Maximus Blevins",
        "Zahra Huerta",
        "Brantley Wiley",
        "Calista Valentine",
        "Kian Blackburn",
        "Arielle Parks",
        "Kellen Caldwell",
        "Anastasia Hendricks",
        "Cassius Conway",
        "Rhea Daly",
        "Jett Hines",
        "Maren Moyer",
        "Talon Hooper",
        "Isolde McPherson",
        "Koda Bolton",
        "Dahlia Shaffer",
        "Ridge Giles",
        "Elowen Holder",
        "Eamon Forbes",
        "Cleo Dorsey",
        "Jalen Pratt",
        "Sylvie Sanford",
        "Finnick Spence",
        "Liv Mercer" };

        internal void TestData()
        {
            Random rand = new();
            List<Student> students = new List<Student>();
            foreach(string name in NAMES)
            {
                Student Student = new()
                {
                    Name = name,
                    Group = rand.Next(5,9),
                    MathScore = rand.Next(0, 11),
                    EnglishScore = rand.Next(0, 11),
                    HistoryScore = rand.Next(0, 11),
                    GeographyScore = rand.Next(0, 11),
                    ChemistryScore = rand.Next(0, 11),
                    ArtScore = rand.Next(0, 11)
                };
                students.Add(Student);
            }
            using AppDbContext db = new AppDbContext();

            db.Students.AddRange(
                students
            );

            db.SaveChanges();
        }
    }
}
